In [7]:
from kaggle_secrets import UserSecretsClient
user_secrets = UserSecretsClient()
GITHUB_ACCESS_TOKEN = user_secrets.get_secret("GITHUB_ACCESS_TOKEN")

In [2]:
!pip install qwen-vl-utils loguru huggingface-hub pydantic
!git config --global user.email "aliaagheis@gmail.com"
!git clone -b explore-datasets-with-actions https://{GITHUB_ACCESS_TOKEN}@github.com/YaraHisham61/Click2Act
%cd Click2Act

Collecting qwen-vl-utils
  Downloading qwen_vl_utils-0.0.14-py3-none-any.whl.metadata (9.0 kB)
Collecting loguru
  Downloading loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.12/dist-packages (1.4.1)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (2.12.3)
Collecting av (from qwen-vl-utils)
  Downloading av-17.0.1-cp311-abi3-manylinux_2_28_x86_64.whl.metadata (4.6 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from qwen-vl-utils) (26.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from qwen-vl-utils) (11.3.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from qwen-vl-utils) (2.32.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub) (1.3.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub) (6.0.3)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub) (1.5.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub) (4.67.3)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface-hub) (0.24.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub) (4.15.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic) (0.4.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->qwen-vl-utils) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->qwen-vl-utils) (2.5.0)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface-hub) (0.24.1)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub) (0.1.2)
Downloading qwen_vl_utils-0.0.14-py3-none-any.whl (8.1 kB)
Downloading loguru-0.7.3-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 2.8 MB/s eta 0:00:00
Downloading av-17.0.1-cp311-abi3-manylinux_2_28_x86_64.whl (36.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.3/36.3 MB 59.0 MB/s eta 0:00:00:00:0100:01
Installing collected packages: loguru, av, qwen-vl-utils
Successfully installed av-17.0.1 loguru-0.7.3 qwen-vl-utils-0.0.14
Cloning into 'Click2Act'...
remote: Enumerating objects: 1070, done.
remote: Counting objects: 100% (163/163), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 1070 (delta 154), reused 148 (delta 146), pack-reused 907 (from 2)
Receiving objects: 100% (1070/1070), 163.28 MiB | 42.89 MiB/s, done.
Resolving deltas: 100% (490/490), done.
/kaggle/working/Click2Act

In [3]:
!ls models

ls: cannot access 'models': No such file or directory

In [4]:
!git config pull.rebase true

In [16]:
!git pull origin explore-datasets-with-actions

remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0 (from 0)
Unpacking objects: 100% (5/5), 506 bytes | 506.00 KiB/s, done.
From https://github.com/YaraHisham61/Click2Act
 * branch            explore-datasets-with-actions -> FETCH_HEAD
   2fa7ecf..85e35e7  explore-datasets-with-actions -> origin/explore-datasets-with-actions
Successfully rebased and updated refs/heads/explore-datasets-with-actions.

In [6]:
!ls /kaggle/input/datasets/aliaagheis/android-control/data

test-00000.parquet  test-00008.parquet	test-00016.parquet  test-00024.parquet
test-00001.parquet  test-00009.parquet	test-00017.parquet  test-00025.parquet
test-00002.parquet  test-00010.parquet	test-00018.parquet  test-00026.parquet
test-00003.parquet  test-00011.parquet	test-00019.parquet  test-00027.parquet
test-00004.parquet  test-00012.parquet	test-00020.parquet  test-00028.parquet
test-00005.parquet  test-00013.parquet	test-00021.parquet  test-00029.parquet
test-00006.parquet  test-00014.parquet	test-00022.parquet
test-00007.parquet  test-00015.parquet	test-00023.parquet

In [7]:
!touch experiments/2026-5-1_exp_aguvis_android_control/config/androidcontrol.yaml

In [8]:
%%writefile  experiments/2026-5-1_exp_aguvis_android_control/config/androidcontrol.yaml
class: androidcontrol
params:
  benchmark_path: /kaggle/input/datasets/aliaagheis/android-control/data
  extracted_path: /kaggle/input/datasets/aliaagheis/android-control/data
  repo_id: aliaagheis/android-control

Overwriting experiments/2026-5-1_exp_aguvis_android_control/config/androidcontrol.yaml

In [74]:

%%writefile  experiments/2026-5-1_exp_aguvis_android_control/config/action_scorer.yaml
batch_size: 16
dataset_size: 500
agent: experiments/2026-5-1_exp_aguvis_android_control/config/aguvis.yaml
output_csv: experiments/2026-5-1_exp_aguvis_android_control/action_scorer.csv
benchmark: experiments/2026-5-1_exp_aguvis_android_control/config/androidcontrol.yaml

Overwriting experiments/2026-5-1_exp_aguvis_android_control/config/action_scorer.yaml

In [75]:
!du experiments/2026-5-1_exp_aguvis_android_control/action_scorer.csv -h

160K	experiments/2026-5-1_exp_aguvis_android_control/action_scorer.csv

In [76]:
for i in range(10):
    !python -m src.pipeline.action_scorer "experiments/2026-5-1_exp_aguvis_android_control/config/action_scorer.yaml"
    !git add *
    !git commit -m "kaggle(aguvis|android-control): upload results via kaggle"
    !git push origin explore-datasets-with-actions

2026-05-01 21:58:02.902 | DEBUG    | src.agents.aguvis:__init__:34 - initalize agent with config={'model_path': './models/aguvis-7B-720P', 'temperature': 0, 'max_new_tokens': 1024, 'dtype': 'float16', 'device_map': 'auto', 'repo_id': 'xlangai/Aguvis-7B-720P', 'mode': 'self-plan', 'grounding_system_message': 'You are a GUI agent. You are given a task and a screenshot of the screen. You need to perform a series of pyautogui actions to complete the task.', 'agent_system_message': 'You are a GUI agent. You are given a task and a screenshot of the screen. You need to perform a series of pyautogui actions to complete the task.\n\nYou have access to the following functions:\n- {"name": "mobile.swipe", "description": "Swipe on the screen", "parameters": {"type": "object", "properties": {"from_coord": {"type": "array", "items": {"type": "number"}, "description": "The starting coordinates of the swipe"}, "to_coord": {"type": "array", "items": {"type": "number"}, "description": "The ending coordinates of the swipe"}}, "required": ["from_coord", "to_coord"]}}\n- {"name": "mobile.home", "description": "Press the home button"}\n- {"name": "mobile.back", "description": "Press the back button"}\n- {"name": "mobile.wait", "description": "wait for the change to happen", "parameters": {"type": "object", "properties": {"seconds": {"type": "number", "description": "The seconds to wait"}}, "required": ["seconds"]}}\n- {"name": "mobile.long_press", "description": "Long press on the screen", "parameters": {"type": "object", "properties": {"x": {"type": "number", "description": "The x coordinate of the long press"}, "y": {"type": "number", "description": "The y coordinate of the long press"}}, "required": ["x", "y"]}}\n- {"name": "mobile.open_app", "description": "Open an app on the device", "parameters": {"type": "object", "properties": {"app_name": {"type": "string", "description": "The name of the app to open"}}, "required": ["app_name"]}}\n', 'user_message_template': 'Please generate the next move according to the ui screenshot, instruction and previous actions.\n\nInstruction: {overall_goal}\n\nPrevious actions:\n{previous_actions}\n', 'low_level_instruction': None}
Loading weights: 100%|█| 730/730 [00:53<00:00, 13.57it/s, Materializing param=mo
The image processor of type `Qwen2VLImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`.
batches:   0%|                                           | 0/32 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:   3%|█                                  | 1/32 [00:48<25:10, 48.74s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:   6%|██▏                                | 2/32 [01:38<24:40, 49.36s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:   9%|███▎                               | 3/32 [02:29<24:08, 49.96s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  12%|████▍                              | 4/32 [03:20<23:38, 50.67s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  16%|█████▍                             | 5/32 [04:11<22:47, 50.63s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  19%|██████▌                            | 6/32 [05:03<22:10, 51.18s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  22%|███████▋                           | 7/32 [05:54<21:18, 51.14s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  25%|████████▊                          | 8/32 [06:49<20:50, 52.12s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  28%|█████████▊                         | 9/32 [07:41<19:59, 52.15s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  31%|██████████▋                       | 10/32 [08:33<19:06, 52.12s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  34%|███████████▋                      | 11/32 [09:25<18:17, 52.25s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  38%|████████████▊                     | 12/32 [10:18<17:27, 52.40s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  41%|█████████████▊                    | 13/32 [11:10<16:34, 52.33s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  44%|██████████████▉                   | 14/32 [12:02<15:38, 52.16s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  47%|███████████████▉                  | 15/32 [12:54<14:44, 52.05s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  50%|█████████████████                 | 16/32 [13:45<13:50, 51.90s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  53%|██████████████████                | 17/32 [14:37<12:57, 51.85s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  56%|███████████████████▏              | 18/32 [15:29<12:04, 51.72s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  59%|████████████████████▏             | 19/32 [16:20<11:12, 51.75s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  62%|█████████████████████▎            | 20/32 [17:12<10:20, 51.70s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  66%|██████████████████████▎           | 21/32 [18:04<09:28, 51.70s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  69%|███████████████████████▍          | 22/32 [18:55<08:37, 51.75s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  72%|████████████████████████▍         | 23/32 [19:47<07:45, 51.76s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  75%|█████████████████████████▌        | 24/32 [20:39<06:54, 51.83s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  78%|██████████████████████████▌       | 25/32 [21:30<05:59, 51.43s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  81%|███████████████████████████▋      | 26/32 [22:22<05:10, 51.80s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  84%|████████████████████████████▋     | 27/32 [23:15<04:20, 52.03s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  88%|█████████████████████████████▊    | 28/32 [24:07<03:27, 51.91s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  91%|██████████████████████████████▊   | 29/32 [24:59<02:36, 52.11s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  94%|███████████████████████████████▉  | 30/32 [25:51<01:43, 51.97s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  97%|████████████████████████████████▉ | 31/32 [26:44<00:52, 52.38s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches: 100%|██████████████████████████████████| 32/32 [26:59<00:00, 50.60s/it]
The following paths are ignored by one of your .gitignore files:
models
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
[explore-datasets-with-actions 2f2fbb1] kaggle(aguvis|android-control): upload results via kaggle
 2 files changed, 501 insertions(+), 1 deletion(-)
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 4 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 34.06 KiB | 3.78 MiB/s, done.
Total 7 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/YaraHisham61/Click2Act
   76c7b19..2f2fbb1  explore-datasets-with-actions -> explore-datasets-with-actions
2026-05-01 22:27:46.010 | DEBUG    | src.agents.aguvis:__init__:34 - initalize agent with config={'model_path': './models/aguvis-7B-720P', 'temperature': 0, 'max_new_tokens': 1024, 'dtype': 'float16', 'device_map': 'auto', 'repo_id': 'xlangai/Aguvis-7B-720P', 'mode': 'self-plan', 'grounding_system_message': 'You are a GUI agent. You are given a task and a screenshot of the screen. You need to perform a series of pyautogui actions to complete the task.', 'agent_system_message': 'You are a GUI agent. You are given a task and a screenshot of the screen. You need to perform a series of pyautogui actions to complete the task.\n\nYou have access to the following functions:\n- {"name": "mobile.swipe", "description": "Swipe on the screen", "parameters": {"type": "object", "properties": {"from_coord": {"type": "array", "items": {"type": "number"}, "description": "The starting coordinates of the swipe"}, "to_coord": {"type": "array", "items": {"type": "number"}, "description": "The ending coordinates of the swipe"}}, "required": ["from_coord", "to_coord"]}}\n- {"name": "mobile.home", "description": "Press the home button"}\n- {"name": "mobile.back", "description": "Press the back button"}\n- {"name": "mobile.wait", "description": "wait for the change to happen", "parameters": {"type": "object", "properties": {"seconds": {"type": "number", "description": "The seconds to wait"}}, "required": ["seconds"]}}\n- {"name": "mobile.long_press", "description": "Long press on the screen", "parameters": {"type": "object", "properties": {"x": {"type": "number", "description": "The x coordinate of the long press"}, "y": {"type": "number", "description": "The y coordinate of the long press"}}, "required": ["x", "y"]}}\n- {"name": "mobile.open_app", "description": "Open an app on the device", "parameters": {"type": "object", "properties": {"app_name": {"type": "string", "description": "The name of the app to open"}}, "required": ["app_name"]}}\n', 'user_message_template': 'Please generate the next move according to the ui screenshot, instruction and previous actions.\n\nInstruction: {overall_goal}\n\nPrevious actions:\n{previous_actions}\n', 'low_level_instruction': None}
Loading weights: 100%|█| 730/730 [00:53<00:00, 13.56it/s, Materializing param=mo
The image processor of type `Qwen2VLImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`.
batches:   0%|                                           | 0/32 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:   3%|█                                  | 1/32 [00:55<28:51, 55.84s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:   6%|██▏                                | 2/32 [01:47<26:48, 53.63s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:   9%|███▎                               | 3/32 [02:39<25:32, 52.84s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  12%|████▍                              | 4/32 [03:32<24:42, 52.93s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  16%|█████▍                             | 5/32 [04:24<23:33, 52.34s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  19%|██████▌                            | 6/32 [05:15<22:36, 52.16s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  22%|███████▋                           | 7/32 [06:08<21:45, 52.21s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  25%|████████▊                          | 8/32 [07:00<20:51, 52.13s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  28%|█████████▊                         | 9/32 [07:51<19:55, 51.97s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  31%|██████████▋                       | 10/32 [08:42<18:54, 51.57s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  34%|███████████▋                      | 11/32 [09:34<18:04, 51.64s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  38%|████████████▊                     | 12/32 [10:26<17:14, 51.72s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  41%|█████████████▊                    | 13/32 [11:20<16:35, 52.38s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  44%|██████████████▉                   | 14/32 [12:11<15:35, 51.99s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  47%|███████████████▉                  | 15/32 [13:02<14:41, 51.87s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  50%|█████████████████                 | 16/32 [13:53<13:45, 51.58s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  53%|██████████████████                | 17/32 [14:45<12:54, 51.63s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  56%|███████████████████▏              | 18/32 [15:37<12:03, 51.67s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  59%|████████████████████▏             | 19/32 [16:29<11:13, 51.80s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  62%|█████████████████████▎            | 20/32 [17:21<10:22, 51.89s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  66%|██████████████████████▎           | 21/32 [18:13<09:31, 51.93s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  69%|███████████████████████▍          | 22/32 [19:05<08:39, 51.91s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  72%|████████████████████████▍         | 23/32 [19:57<07:47, 51.97s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  75%|█████████████████████████▌        | 24/32 [20:49<06:56, 52.01s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  78%|██████████████████████████▌       | 25/32 [21:40<06:01, 51.63s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  81%|███████████████████████████▋      | 26/32 [22:32<05:10, 51.72s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  84%|████████████████████████████▋     | 27/32 [23:24<04:18, 51.77s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  88%|█████████████████████████████▊    | 28/32 [24:15<03:26, 51.53s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  91%|██████████████████████████████▊   | 29/32 [25:06<02:34, 51.48s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  94%|███████████████████████████████▉  | 30/32 [25:57<01:42, 51.47s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches:  97%|████████████████████████████████▉ | 31/32 [26:49<00:51, 51.57s/it]Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.
batches: 100%|██████████████████████████████████| 32/32 [27:04<00:00, 50.77s/it]
The following paths are ignored by one of your .gitignore files:
models
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
[explore-datasets-with-actions 322275a] kaggle(aguvis|android-control): upload results via kaggle
 1 file changed, 500 insertions(+)
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 4 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 23.60 KiB | 2.14 MiB/s, done.
Total 5 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/YaraHisham61/Click2Act
   2f2fbb1..322275a  explore-datasets-with-actions -> explore-datasets-with-actions
2026-05-01 22:57:27.961 | DEBUG    | src.agents.aguvis:__init__:34 - initalize agent with config={'model_path': './models/aguvis-7B-720P', 'temperature': 0, 'max_new_tokens': 1024, 'dtype': 'float16', 'device_map': 'auto', 'repo_id': 'xlangai/Aguvis-7B-720P', 'mode': 'self-plan', 'grounding_system_message': 'You are a GUI agent. You are given a task and a screenshot of the screen. You need to perform a series of pyautogui actions to complete the task.', 'agent_system_message': 'You are a GUI agent. You are given a task and a screenshot of the screen. You need to perform a series of pyautogui actions to complete the task.\n\nYou have access to the following functions:\n- {"name": "mobile.swipe", "description": "Swipe on the screen", "parameters": {"type": "object", "properties": {"from_coord": {"type": "array", "items": {"type": "number"}, "description": "The starting coordinates of the swipe"}, "to_coord": {"type": "array", "items": {"type": "number"}, "description": "The ending coordinates of the swipe"}}, "required": ["from_coord", "to_coord"]}}\n- {"name": "mobile.home", "description": "Press the home button"}\n- {"name": "mobile.back", "description": "Press the back button"}\n- {"name": "mobile.wait", "description": "wait for the change to happen", "parameters": {"type": "object", "properties": {"seconds": {"type": "number", "description": "The seconds to wait"}}, "required": ["seconds"]}}\n- {"name": "mobile.long_press", "description": "Long press on the screen", "parameters": {"type": "object", "properties": {"x": {"type": "number", "description": "The x coordinate of the long press"}, "y": {"type": "number", "description": "The y coordinate of the long press"}}, "required": ["x", "y"]}}\n- {"name": "mobile.open_app", "description": "Open an app on the device", "parameters": {"type": "object", "properties": {"app_name": {"type": "string", "description": "The name of the app to open"}}, "required": ["app_name"]}}\n', 'user_message_template': 'Please generate the next move according to the ui screenshot, instruction and previous actions.\n\nInstruction: {overall_goal}\n\nPrevious actions:\n{previous_actions}\n', 'low_level_instruction': None}
Loading weights: 100%|█| 730/730 [00:44<00:00, 16.48it/s, Materializing param=mo
The image processor of type `Qwen2VLImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`.
batches:   0%|                                           | 0/32 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Setting `pad_token_id` to `eos_token_id`:151658 for open-end generation.

In [34]:
import pandas as pd

In [57]:
!git reset --hard 5c7bf84073e389d30ff2d03d036243dd4af7626b

HEAD is now at 5c7bf84 kaggle(aguvis|android-control): upload results via kaggle

In [58]:
!git log

commit 5c7bf84073e389d30ff2d03d036243dd4af7626b (HEAD -> explore-datasets-with-actions)
Author: root <aliaagheis@gmail.com>
Date:   Fri May 1 21:39:45 2026 +0000

    kaggle(aguvis|android-control): upload results via kaggle

commit 85e35e736ed0a5d1e47432ac9c90dd8270bcab9b (origin/explore-datasets-with-actions)
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Sat May 2 00:43:10 2026 +0300

    ref android-control

commit 2fa7ecf4c8d0ba8d4b17de92196bd8db11bc56ee
Merge: 00b09ae d32778c
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Sat May 2 00:10:22 2026 +0300

    Merge branch 'explore-datasets-with-actions' of https://github.com/YaraHisham61/Click2Act into explore-datasets-with-actions

commit 00b09ae43533e49eced7cb90092e6d851845aa1c
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Sat May 2 00:10:01 2026 +0300

    fix parser

commit d32778c560920d87bf3c61384e9dd007014f01b8
Author: root <aliaagheis@gmail.com>
Date:   Fri May 1 20:49:30 2026 +0000

    kaggle(aguvis|android-control): upload results via kaggle

commit 7bed59e82f37d0af2b57162d590d089eca85d0b4
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Fri May 1 23:44:11 2026 +0300

    fix(action-scorer)

commit 2172656ebf50ffd2c822432fc48c272aec823a6f
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Fri May 1 23:30:06 2026 +0300

    fix(android-control): add extract path

commit a5f469530d9fec67d16423ed63770ed4b6d5d237
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Fri May 1 22:54:39 2026 +0300

    fix(small): android-control

commit cde2ce862f80d83a7a65758022e2ee94893c06f9
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Fri May 1 22:49:47 2026 +0300

    fix(small): aguvis

commit 9cbf65f149758d7af503921187a6d92fd385c430
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Fri May 1 22:46:54 2026 +0300

    fix(small): parser

commit 33cb56c572e0b55de84b23e6c2b8de9e015f2461 (origin/kaggle-aguvis-on-android-control)
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Fri May 1 22:40:04 2026 +0300

    configs: add config for action_scorer, aguvis experiment

commit 2d9e6da79639e46d40449c4ea93d5676e311da1c
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Fri May 1 22:32:34 2026 +0300

    agent(aguvis): allow it to work with predict action, pipeline(action_scorer) add new script

commit 55023948f314ce04d3df84ebf1782e91b4c1b7ce
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Fri May 1 22:31:48 2026 +0300

    data(android-control) add android control benchmark inside framework

commit 15031b48646e51ddb79c9f66b3f34b347bd6a54f
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Fri May 1 21:50:10 2026 +0300

    feat(parser-multiple-outputs): support multiple outputs for pyguiout and aguvis mobile

commit 0164ff2416205c239dd73d3252e17e289fc7b740
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Fri May 1 21:41:54 2026 +0300

    clean(imports)

commit 0f8c8f8c14e8dfb0f419c59e01510648515e853c
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Fri May 1 21:41:32 2026 +0300

    data(one-step-eval): explore multiple dataset for one single step evaluation

commit 47827e30b9b4d9bd0161b621bfe79a39239f3526
Author: mennamohamed0207 <menamohamed0207@gmail.com>
Date:   Sat Apr 25 23:51:40 2026 +0000

    expr(ui-agile): upload results ui-agile on screenspotpro

commit 135c77093ed98668ae45d86542f8b3b892070530
Author: mennamohamed0207 <menamohamed0207@gmail.com>
Date:   Sun Apr 26 02:34:05 2026 +0300

    undo torch type

commit a6d7cac9a09779f62b9da3beb23dbd74278a33a0
Author: mennamohamed0207 <menamohamed0207@gmail.com>
Date:   Sat Apr 25 23:25:08 2026 +0000

    expr(ui-agile): upload results ui-agile on screenspotpro

commit 364d72015ac087bec7db4faa93dfde844a77704e
Author: mennamohamed0207 <menamohamed0207@gmail.com>
Date:   Sun Apr 26 02:06:57 2026 +0300

    editing param

commit af649a5075a367bd9835eabc9a22aab2c97acd70
Author: mennamohamed0207 <menamohamed0207@gmail.com>
Date:   Sun Apr 26 00:46:09 2026 +0300

    adding base of ui-agile

commit 338b9cad535d9398b804c86d209f56bc1940362d (origin/dev)
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Wed Apr 22 08:00:49 2026 +0200

    Update Experiements Reports of AGUVIS and HOLO2 on ScreenSpot-Pro

commit 04f64dba9b90433a7694c71a0da152a244d17dbb
Author: aliaa gheis <aliaagheis@gmail.com>
Date:   Mon Apr 20 18:35:05 2026 +0200

    Add AGUVIS, HOLO2, ScreenSpot-Pro, Expr (AGUVIS on Screenspot)

    * exp(benchmarks): explore different benchmarsk inside docs

    * update rules for ai; add ai disclamir in readme

    * add screenspot benchmark exploration

    * update notes of omniparser

    * data: add scripts to download datasets, models

    * docs: add installation document

    * docs(install): document paddleocr pin and typing_extensions fix

    PaddleOCR 3.x dropped legacy parameters used by OmniParser; pin to 2.8.0.
    Document force-reinstall fix for Sentinel ImportError from stale conda-placed
    typing_extensions file conflicting with pip-upgraded dist-info.

    * chore(readme): add imgs and models dirs to folder structure

    * chore(deps): add ui-tars>=0.5.0 dependency

    * data(scripts): add ScreenSpot dataset download script

    * feat(scripts): add Qwen2.5-VL serve script and model download

    * feat(src): add source package with constants, utils, and C2A palette

    * exp(omniparser): add smoke-check notebook and sample images

    * data(references): update OmniParser solution PDF

    * docs(claude): add vision models budget guide

    * docs(claude): add todolist, plan architecture of project

    * docs(omniparser) add small summary to omniparser with smoke results

    * exp(aguvis,uitars): add smoke-check notebook

    * exp(halo2): add smoke-check notebook

    * exp(screenspot-pro): add download script, load images and bboxs

    * docs(claude): change in architecture of project

    * core(init): initalize architecutr, add aguvis and screenspot pro

    * exp(aguvis|screenspotpro): add config file

    * chore(deps): add loguru pydanti

    * chore(configs): add default config for aguvis and screenspotpro

    * fix(imports): add src as parent module

    * fix(pydantic): allow to add image as arbitary type

    * feat(agent) batch processing

    * expr(speedup)

    * fix(aguvis) output parser

    * results(aguvis|screenspotpro) add recent results

    * expr: upload results augvis

    * feat(halo2): add new agent halo2 with grounding functions

    * ref(grounder): refine grounder to output raw output to debug errors

    * chores(expr) add kaggle notebook that run aguvis on screenspotpro

    * chores(expr): start new experiement halo2 on screenspot

    * expr(profiling): profiling grounder on halo2

    * chores(halo2): run profiling with results/ add inference

    * fix(grounder) collect garabage and clean cache

    * optim(screenspotpro) sorting samples based on image area

    * exp(aguvis): evaluate results of aguvis on screenspot-pro

    * docs(README) add framework guidlines

commit 53ebb4e5f686caafa0265cfa6e9176f920c3dda0
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Sat Apr 18 06:55:16 2026 +0200

    exp(screenspot-pro): add download script, load images and bboxs

commit ef6bbe6b7b1542a52fb94db67eaba5e26830868a
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Sat Apr 18 05:06:13 2026 +0200

    exp(halo2): add smoke-check notebook

commit b938881d2d0449388ab791f1d355bff7464a9d3d
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Sat Apr 18 03:25:05 2026 +0200

    exp(aguvis,uitars): add smoke-check notebook

commit 3c33a04c0c3bf7990efa4e6bccfd2547f9f82206
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Mon Apr 13 02:34:01 2026 +0200

    docs(omniparser) add small summary to omniparser with smoke results

commit 0e1d290d5ccfebe1ee02e1d54aa63d1756dfa2dd
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Mon Apr 13 02:14:36 2026 +0200

    docs(claude): add todolist, plan architecture of project

commit 527639e85c6009332e25592a289f13324cb66eb4
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Mon Apr 13 02:13:13 2026 +0200

    docs(claude): add vision models budget guide

commit 3f69d829ce9a5f994e28028b80d042356512b5f9
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Mon Apr 13 02:13:06 2026 +0200

    data(references): update OmniParser solution PDF

commit 885d9446845654f0867abf9c75e60d7454c8e750
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Mon Apr 13 02:12:58 2026 +0200

    exp(omniparser): add smoke-check notebook and sample images

commit dece37bdeae904b795f338379a38681ca778af02
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Mon Apr 13 02:12:52 2026 +0200

    feat(src): add source package with constants, utils, and C2A palette

commit 7b61b0e981a1360217f1be78b910cc8017a18ffb
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Mon Apr 13 02:12:45 2026 +0200

    feat(scripts): add Qwen2.5-VL serve script and model download

commit bb312376b7d5aed258c3210ee9d02550a7d4c7ac
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Mon Apr 13 02:10:45 2026 +0200

    data(scripts): add ScreenSpot dataset download script

commit befe29837bcd828b8ca8f84d72e268908c0549b3
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Mon Apr 13 02:10:42 2026 +0200

    chore(deps): add ui-tars>=0.5.0 dependency

commit 864fb2a84338eac3073690d6fc90335fc2a81f09
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Mon Apr 13 02:10:38 2026 +0200

    chore(readme): add imgs and models dirs to folder structure

commit 16633aff98ce008c493b055a32dce6b2cadd065c
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Mon Apr 13 02:10:30 2026 +0200

    docs(install): document paddleocr pin and typing_extensions fix

    PaddleOCR 3.x dropped legacy parameters used by OmniParser; pin to 2.8.0.
    Document force-reinstall fix for Sentinel ImportError from stale conda-placed
    typing_extensions file conflicting with pip-upgraded dist-info.

commit 15df893f91e8079e9f3e85e18e03068b641197e1
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Mon Apr 6 06:25:27 2026 +0200

    docs: add installation document

commit 16676427d990744dd09a359f25b08c604c6dd32b
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Mon Apr 6 06:25:09 2026 +0200

    data: add scripts to download datasets, models

commit 99ca284e2333f1abc01a908d76e889e7009c3100
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Tue Mar 31 07:25:09 2026 +0200

    update notes of omniparser

commit 8c072b2101d2e509c7b906db6c66c4e09691599c
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Tue Mar 31 07:24:52 2026 +0200

    add screenspot benchmark exploration

commit 0fe0a2ddc1073983f3fb7fe644685e2f12fedfb5
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Tue Mar 31 07:24:22 2026 +0200

    update rules for ai; add ai disclamir in readme

commit 3036be97d658d37fd074a86bab6f8c132a1bf503
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Mon Mar 30 07:47:27 2026 +0200

    exp(benchmarks): explore different benchmarsk inside docs

commit 9c5a399db82e25b59b5d0b351676f822e7c62adb (origin/master, origin/HEAD)
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Mon Mar 30 04:51:57 2026 +0200

    update readme with AI transparency

commit 3971669fe55097ca1c4c7c7a06ca50b90032daa5
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Mon Mar 30 04:49:42 2026 +0200

    add ai transparent rules for both AI tools (gemini-claude)

commit 6f3bbc4270f435927f6fe4715fbe9bf9b1612b81
Author: aliaagheisX <aliaagheis@gmail.com>
Date:   Mon Mar 30 04:21:56 2026 +0200

    init repo; upload purposal, refs

commit 588319007f098a067e39592014647ec5578c54df
Author: Yara Hisham <yara.mahrous01@eng-st.cu.edu.eg>
Date:   Tue Mar 24 20:10:25 2026 +0200

    Add README

In [68]:
df = pd.read_csv("experiments/2026-5-1_exp_aguvis_android_control/action_scorer.csv", index_col=0)

In [69]:
df

,task,annotation,raw_output
idx,,,
0,Open the Cx file Explorer app,"{'episode_id': 27, 'goal': 'Open the Cx file E...","{""coordinate"":null,""action_type"":""open_app"",""t..."
1,Click on the square icon next to the Flowers f...,"{'episode_id': 27, 'goal': 'Open the Cx file E...","{""coordinate"":[0.9509,0.2546],""action_type"":""c..."
2,Click on the rename option at the bottom of th...,"{'episode_id': 27, 'goal': 'Open the Cx file E...","{""coordinate"":[0.5,0.9404],""action_type"":""clic..."
3,Click on the cross icon on the keyboard,"{'episode_id': 27, 'goal': 'Open the Cx file E...","{""coordinate"":[0.9204,0.8392],""action_type"":""c..."
4,Enter the folder name as Flora,"{'episode_id': 27, 'goal': 'Open the Cx file E...","{""coordinate"":null,""action_type"":null,""text"":n..."
...,...,...,...
304,Open the artsy app.,"{'episode_id': 662, 'goal': ""Browse Leonardo D...","{""coordinate"":null,""action_type"":""open_app"",""t..."
305,Click on the search icon at the bottom.,"{'episode_id': 662, 'goal': ""Browse Leonardo D...","{""coordinate"":[0.3,0.9463],""action_type"":""clic..."
306,"Type ""Leonardo Da Vinci Mona lisa's painting"" ...","{'episode_id': 662, 'goal': ""Browse Leonardo D...","{""coordinate"":null,""action_type"":""write"",""text..."
307,Click on the Search icon at the bottom right c...,"{'episode_id': 662, 'goal': ""Browse Leonardo D...","{""coordinate"":[0.9204,0.9038],""action_type"":""c..."
308,"Click on the tab ""Lenardo da vinci"".","{'episode_id': 662, 'goal': ""Browse Leonardo D...","{""coordinate"":[0.55,0.3021],""action_type"":""cli..."

In [65]:
import ast

df['annotation'] =df['annotation'].apply(lambda x: {k:v for k,v in ast.literal_eval(x).items() if k!="screenshot_b64"})

In [66]:
df

,task,annotation,raw_output
idx,,,
0,Open the Cx file Explorer app,"{'episode_id': 27, 'goal': 'Open the Cx file E...","{""coordinate"":null,""action_type"":""open_app"",""t..."
1,Click on the square icon next to the Flowers f...,"{'episode_id': 27, 'goal': 'Open the Cx file E...","{""coordinate"":[0.9509,0.2546],""action_type"":""c..."
2,Click on the rename option at the bottom of th...,"{'episode_id': 27, 'goal': 'Open the Cx file E...","{""coordinate"":[0.5,0.9404],""action_type"":""clic..."
3,Click on the cross icon on the keyboard,"{'episode_id': 27, 'goal': 'Open the Cx file E...","{""coordinate"":[0.9204,0.8392],""action_type"":""c..."
4,Enter the folder name as Flora,"{'episode_id': 27, 'goal': 'Open the Cx file E...","{""coordinate"":null,""action_type"":null,""text"":n..."
...,...,...,...
304,Open the artsy app.,"{'episode_id': 662, 'goal': 'Browse Leonardo D...","{""coordinate"":null,""action_type"":""open_app"",""t..."
305,Click on the search icon at the bottom.,"{'episode_id': 662, 'goal': 'Browse Leonardo D...","{""coordinate"":[0.3,0.9463],""action_type"":""clic..."
306,"Type ""Leonardo Da Vinci Mona lisa's painting"" ...","{'episode_id': 662, 'goal': 'Browse Leonardo D...","{""coordinate"":null,""action_type"":""write"",""text..."
307,Click on the Search icon at the bottom right c...,"{'episode_id': 662, 'goal': 'Browse Leonardo D...","{""coordinate"":[0.9204,0.9038],""action_type"":""c..."
308,"Click on the tab ""Lenardo da vinci"".","{'episode_id': 662, 'goal': 'Browse Leonardo D...","{""coordinate"":[0.55,0.3021],""action_type"":""cli..."

In [67]:
df.to_csv("experiments/2026-5-1_exp_aguvis_android_control/action_scorer.csv", index=True)

In [70]:
!git add experiments/2026-5-1_exp_aguvis_android_control/action_scorer.csv

In [72]:
!git commit --amend --no-edit

[explore-datasets-with-actions 76c7b19] kaggle(aguvis|android-control): upload results via kaggle
 Date: Fri May 1 21:39:45 2026 +0000
 2 files changed, 312 insertions(+), 8 deletions(-)
 rewrite experiments/2026-5-1_exp_aguvis_android_control/action_scorer.csv (98%)

In [73]:
!git push origin explore-datasets-with-actions

Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 4 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 13.47 KiB | 4.49 MiB/s, done.
Total 7 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/YaraHisham61/Click2Act
   85e35e7..76c7b19  explore-datasets-with-actions -> explore-datasets-with-actions